---
- hosts: all
  vars_files:
    - vars.yml

  tasks:
    - name: Get start time
      block:
        - setup:
            filter: ansible_date_time
          register: start_time
        - set_fact:
            start_time: "{{ lookup('pipe','date \"+%T %Z %F\"') }}"
        - name: Start Time
          debug:
            msg: "{{ start_time }}"
      delegate_to: localhost
      tags: always

# Make sure all VMs already migrated before entering maintenance mode and patching

    - name: Enter Maintenance Mode
      shell: esxcli system maintenanceMode set --enable true
      ignore_errors: yes

    - name: Patch it
      shell: esxcli software profile update -d {{ PATCH_FILE_PATH }} -p {{ PATCH_PROFILE }} --no-hardware-warning

    - name: Reboot
      shell: esxcli system shutdown reboot --reason "patching"
      ignore_errors: yes

    - name: Get end time
      block:
        - setup:
            filter: ansible_date_time
          register: end_time
        - set_fact:
            end_time: "{{ lookup('pipe','date \"+%T %Z %F\"') }}"
        - name: End Time
          debug:
            msg: "{{ end_time }}"
      delegate_to: localhost
      tags: always

